/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SkyRouteImport } from './routes/sky'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacetFacetRouteImport } from './routes/facet.$facet'
import { Route as RoomSlugRouteImport } from './routes/$room.$slug'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyRoute = SkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacetFacetRoute = FacetFacetRouteImport.update({
  id: '/facet/$facet',
  path: '/facet/$facet',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/$room/$slug',
  path: '/$room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/salon': typeof SalonRoute
  '/sky': typeof SkyRoute
  '/studio': typeof StudioRoute
  '/study': typeof StudyRoute
  '/$room/$slug': typeof RoomSlugRoute
  '/facet/$facet': typeof FacetFacetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/salon': typeof SalonRoute
  '/sky': typeof SkyRoute
  '/studio': typeof StudioRoute
  '/study': typeof StudyRoute
  '/$room/$slug': typeof RoomSlugRoute
  '/facet/$facet': typeof FacetFacetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/salon': typeof SalonRoute
  '/sky': typeof SkyRoute
  '/studio': typeof StudioRoute
  '/study': typeof StudyRoute
  '/$room/$slug': typeof RoomSlugRoute
  '/facet/$facet': typeof FacetFacetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/garden'
    | '/salon'
    | '/sky'
    | '/studio'
    | '/study'
    | '/$room/$slug'
    | '/facet/$facet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/garden'
    | '/salon'
    | '/sky'
    | '/studio'
    | '/study'
    | '/$room/$slug'
    | '/facet/$facet'
  id:
    | '__root__'
    | '/'
    | '/garden'
    | '/salon'
    | '/sky'
    | '/studio'
    | '/study'
    | '/$room/$slug'
    | '/facet/$facet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GardenRoute: typeof GardenRoute
  SalonRoute: typeof SalonRoute
  SkyRoute: typeof SkyRoute
  StudioRoute: typeof StudioRoute
  StudyRoute: typeof StudyRoute
  RoomSlugRoute: typeof RoomSlugRoute
  FacetFacetRoute: typeof FacetFacetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sky': {
      id: '/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof SkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facet/$facet': {
      id: '/facet/$facet'
      path: '/facet/$facet'
      fullPath: '/facet/$facet'
      preLoaderRoute: typeof FacetFacetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$room/$slug': {
      id: '/$room/$slug'
      path: '/$room/$slug'
      fullPath: '/$room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GardenRoute: GardenRoute,
  SalonRoute: SalonRoute,
  SkyRoute: SkyRoute,
  StudioRoute: StudioRoute,
  StudyRoute: StudyRoute,
  RoomSlugRoute: RoomSlugRoute,
  FacetFacetRoute: FacetFacetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
